# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(275, 400)
        MainWindow.setMinimumSize(QtCore.QSize(275, 400))
        MainWindow.setMaximumSize(QtCore.QSize(275, 400))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_voteMenu = QtWidgets.QLabel(self.centralwidget)
        self.label_voteMenu.setGeometry(QtCore.QRect(30, 10, 201, 31))
        self.label_voteMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_voteMenu.setScaledContents(True)
        self.label_voteMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_voteMenu.setObjectName("label_voteMenu")
        self.pushButton_Vote = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Vote.setGeometry(QtCore.QRect(20, 210, 100, 51))
        self.pushButton_Vote.setObjectName("pushButton_Vote")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(150, 210, 100, 51))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(20, 280, 231, 71))
        self.label_output.setObjectName("label_output")
        self.input_voterID = QtWidgets.QLineEdit(self.centralwidget)
        self.input_voterID.setGeometry(QtCore.QRect(120, 60, 131, 21))
        self.input_voterID.setObjectName("input_voterID")
        self.label_voterID = QtWidgets.QLabel(self.centralwidget)
        self.label_voterID.setGeometry(QtCore.QRect(20, 60, 58, 16))
        self.label_voterID.setObjectName("label_voterID")
        self.label_candidate = QtWidgets.QLabel(self.centralwidget)
        self.label_candidate.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label_candidate.setObjectName("label_candidate")
        self.radioButton_John = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_John.setGeometry(QtCore.QRect(120, 120, 99, 20))
        self.radioButton_John.setObjectName("radioButton_John")
        self.buttonGroup_candidates = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_candidates.setObjectName("buttonGroup_candidates")
        self.buttonGroup_candidates.addButton(self.radioButton_John)
        self.radioButton_Jane = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Jane.setGeometry(QtCore.QRect(120, 150, 99, 20))
        self.radioButton_Jane.setObjectName("radioButton_Jane")
        self.buttonGroup_candidates.addButton(self.radioButton_Jane)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 1"))
        self.label_voteMenu.setText(_translate("MainWindow", "VOTE MENU"))
        self.pushButton_Vote.setText(_translate("MainWindow", "VOTE"))
        self.pushButton_Exit.setText(_translate("MainWindow", "EXIT"))
        self.label_output.setText(_translate("MainWindow", "Welcome!"))
        self.label_voterID.setText(_translate("MainWindow", "Voter ID:"))
        self.label_candidate.setText(_translate("MainWindow", "Candidate:"))
        self.radioButton_John.setText(_translate("MainWindow", "John"))
        self.radioButton_Jane.setText(_translate("MainWindow", "Jane"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
